version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - depguard
    - revive
    - nlreturn
    - ireturn
    - nonamedreturns
    - staticcheck
    - gochecknoglobals
    - wrapcheck
    - tagliatelle
    - varnamelen
    - mnd
    - exhaustruct
    - godot
    - contextcheck
    - noinlineerr
  exclusions:
    paths:
    - (.+)_test\.go
